extends Resource
class_name ControlScheme


const DEFAULT_BLANK = {
	"MOVE LEFT" = KEY_NONE, "MOVE RIGHT" = KEY_NONE, "MOVE UP" = KEY_NONE, "MOVE DOWN" = KEY_NONE,
	"TAG" = KEY_NONE, "SPECIAL" = KEY_NONE, "JUMP" = KEY_NONE, "ACTION" = KEY_NONE,
	"CHARACTER TOGGLE DOWN" = KEY_NONE, "CHARACTER TOGGLE UP" = KEY_NONE, "START/PAUSE" = KEY_NONE,
	"SHOW MAP" = KEY_NONE, "LOOK UP" = KEY_NONE, "LOOK DOWN" = KEY_NONE, "LOOK LEFT" = KEY_NONE,
	"LOOK RIGHT" = KEY_NONE, "UP" = KEY_NONE, "DOWN" = KEY_NONE, "LEFT" = KEY_NONE, "RIGHT" = KEY_NONE,
}
const DEFAULT_K = {
	"MOVE LEFT" = KEY_A, "MOVE RIGHT" = KEY_D, "MOVE UP" = KEY_W, "MOVE DOWN" = KEY_S,"TAG" = KEY_U,
	"SPECIAL" = KEY_K, "JUMP" = KEY_J, "ACTION" = KEY_H, "CHARACTER TOGGLE DOWN" = KEY_CTRL,
	"CHARACTER TOGGLE UP" = KEY_SPACE, "START/PAUSE" = KEY_ENTER, "SHOW MAP" = KEY_M,
	"LOOK LEFT" = KEY_L, "LOOK RIGHT" = KEY_APOSTROPHE, "LOOK UP" = KEY_P, "LOOK DOWN" = KEY_SEMICOLON,
	"UP" = KEY_NONE, "DOWN" = KEY_NONE, "LEFT" = KEY_NONE, "RIGHT" = KEY_NONE,
}
const DEFAULT_K2 = {
	"MOVE LEFT" = KEY_LEFT, "MOVE RIGHT" = KEY_RIGHT, "MOVE UP" = KEY_UP, "MOVE DOWN" = KEY_DOWN,
	"TAG"=KEY_KP_5, "SPECIAL" = KEY_KP_3, "JUMP" = KEY_KP_2, "ACTION" = KEY_KP_1,
	"CHARACTER TOGGLE DOWN" = KEY_SHIFT, "CHARACTER TOGGLE UP" = KEY_KP_0, "START/PAUSE" = KEY_KP_ENTER,
	"SHOW MAP" = KEY_KP_PERIOD, "LOOK LEFT" = KEY_DELETE, "LOOK RIGHT" = KEY_PAGEDOWN, "LOOK UP" = KEY_HOME,
	"LOOK DOWN" = KEY_END, "UP" = KEY_NONE, "DOWN" = KEY_NONE, "LEFT" = KEY_NONE, "RIGHT" = KEY_NONE,
}
const DEFAULT_J = {
	"MOVE LEFT" = [JOY_AXIS_LEFT_X], "MOVE RIGHT" = [JOY_AXIS_LEFT_X],
	"MOVE UP" = [JOY_AXIS_LEFT_Y], "MOVE DOWN" = [JOY_AXIS_LEFT_Y],
	"TAG" = JOY_BUTTON_Y, "SPECIAL" = JOY_BUTTON_B, "JUMP" = JOY_BUTTON_A, "ACTION" = JOY_BUTTON_X,
	"CHARACTER TOGGLE DOWN" = JOY_BUTTON_LEFT_SHOULDER, "CHARACTER TOGGLE UP" = JOY_BUTTON_RIGHT_SHOULDER,
	"START/PAUSE" = JOY_BUTTON_START, "SHOW MAP" = JOY_BUTTON_BACK, "LOOK LEFT" = [JOY_AXIS_RIGHT_X],
	"LOOK RIGHT" = [JOY_AXIS_RIGHT_X], "LOOK UP" = [JOY_AXIS_RIGHT_Y],
	"LOOK DOWN" = [JOY_AXIS_RIGHT_Y], "UP" = JOY_BUTTON_DPAD_UP, "DOWN" = JOY_BUTTON_DPAD_DOWN,
	"LEFT" = JOY_BUTTON_DPAD_LEFT, "RIGHT" = JOY_BUTTON_DPAD_RIGHT
}

@export var device = false
@export var invert_look_y = false
@export var invert_look_x = false

@export var keybinds = {
	"MOVE LEFT" = KEY_A,
	"MOVE RIGHT" = KEY_D,
	"MOVE UP" = KEY_W,
	"MOVE DOWN" = KEY_S,
	
	"TAG" = KEY_U,
	"SPECIAL" = KEY_K,
	"JUMP" = KEY_J,
	"ACTION" = KEY_H,
	
	"CHARACTER TOGGLE DOWN" = KEY_CTRL,
	"CHARACTER TOGGLE UP" = KEY_SPACE,
	"START/PAUSE" = KEY_ENTER,
	"SHOW MAP" = KEY_M,
	
	"LOOK LEFT" = KEY_L,
	"LOOK RIGHT" = KEY_APOSTROPHE,
	"LOOK UP" = KEY_P,
	"LOOK DOWN" = KEY_SEMICOLON,
	
	"UP" = KEY_NONE,
	"DOWN" = KEY_NONE,
	"LEFT" = KEY_NONE,
	"RIGHT" = KEY_NONE,
}
